WITH RECURSIVE CTE AS(
    SELECT ID, PARENT_ID, 1 AS GENERATION
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
    
     UNION ALL 
    
    SELECT A.ID, A.PARENT_ID, 1 + B.GENERATION GENERATION
      FROM ECOLI_DATA A
     INNER JOIN CTE B ON A.PARENT_ID = B.ID
)
SELECT COUNT(GENERATION) COUNT, GENERATION
  FROM CTE
 WHERE ID NOT IN (SELECT DISTINCT PARENT_ID
                    FROM ECOLI_DATA
                   WHERE PARENT_ID IS NOT NULL)
 GROUP BY GENERATION
 ORDER BY GENERATION