SELECT YEAR, (SIZE - SIZE_OF_COLONY) AS YEAR_DEV, ID
FROM (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
) A JOIN ECOLI_DATA B ON A.YEAR = YEAR(B.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV
;