SELECT A.SCORE, A.EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT EMP_NO, SUM(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE DESC
    LIMIT 1
) A JOIN HR_EMPLOYEES B ON A.EMP_NO = B.EMP_NO
;
